# Generated by Django 4.2.9 on 2024-01-27 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('index', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=255)),
                ('date_of_birth', models.DateTimeField()),
                ('are_you_traveling', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('kobieta', 'Kobieta'), ('mężczyzna', 'Mężczyzna'), ('inne', 'Inne')], max_length=9)),
                ('grades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_and_travel_app.grades')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('big_city_100_km', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('offer_type', models.CharField(choices=[('employer', 'Pracodawca'), ('employee', 'Pracownik')], max_length=20)),
                ('since_when', models.DateTimeField()),
                ('until_when', models.DateTimeField()),
                ('only_for_women', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='work_and_travel_app.category')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_and_travel_app.userprofile')),
            ],
        ),
    ]
