# Generated by Django 4.2.9 on 2024-01-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_and_travel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
