# Generated by Django 4.2.9 on 2024-02-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_and_travel_app', '0002_offer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('job offer', 'Job Offer'), ('job seekers', 'Job Seekers')], max_length=20),
        ),
    ]
