# Generated by Django 4.2.9 on 2024-01-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_and_travel_app', '0002_remove_userprofile_password_remove_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='grades',
        ),
    ]
