# Generated by Django 4.2.9 on 2024-02-01 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_and_travel_app', '0003_alter_offer_offer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='price',
        ),
    ]
