# Generated by Django 4.2.9 on 2024-01-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_and_travel_app', '0003_remove_userprofile_grades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='BaseInformation',
        ),
    ]
