# Generated by Django 4.2.9 on 2024-02-05 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_and_travel_app', '0004_remove_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='work_and_travel_app.offer'),
            preserve_default=False,
        ),
    ]
