# Generated by Django 4.2.9 on 2024-02-05 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_and_travel_app', '0005_message_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='rating',
        ),
        migrations.AddField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
