# Generated by Django 4.2.9 on 2024-02-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_and_travel_app', '0007_alter_baseinformation_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=20240202),
            preserve_default=False,
        ),
    ]
