# Generated by Django 4.2.9 on 2024-02-14 01:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_and_travel_app', '0007_alter_baseinformation_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_and_travel_app.offer'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(help_text='Grade must be between 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
