# Generated by Django 4.2.9 on 2024-02-14 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_and_travel_app', '0008_grade_offer_alter_grade_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='offer',
        ),
        migrations.AddField(
            model_name='grade',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_and_travel_app.message'),
        ),
    ]
