# Generated by Django 4.2.9 on 2024-02-14 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_and_travel_app', '0009_remove_grade_offer_grade_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_and_travel_app.message'),
        ),
    ]
