# Generated by Django 4.2.9 on 2024-02-14 16:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_and_travel_app', '0011_alter_grade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_and_travel_app.grade'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='grade',
            field=models.IntegerField(help_text='Rating must be between 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
