# Generated by Django 4.2.9 on 2024-02-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_and_travel_app', '0013_alter_answer_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='grade',
            new_name='grade_answer',
        ),
    ]
